# languages.py
LANGUAGES = {
    "en": {
        "title": "Data Analysis Pro",
        "login": "Login",
        "signup": "Sign Up",
        "username": "Username",
        "password": "Password",
        "email": "Email",
        "confirm_password": "Confirm Password",
        "login_btn": "Login",
        "sign_up_btn": "Sign Up",
        "fill_fields": "Please fill all fields",
        "account_exists": "Account already exists",
        "success_signup": "Account created successfully!",
        "error_login": "Invalid username or password",
        "welcome": "Welcome",
        "logout_btn": "Logout",
        "admin_dashboard": "Admin Dashboard",
        "subscription_warning": "Your subscription ends in {days} days",
        "upload_file": "Upload Dataset",
        "dashboard": "Dashboard",
        "analytics": "Analytics",
        "machine_learning": "Machine Learning",
        "data_management": "Data Management",
        "settings": "Settings",
        "store": "Upgrade Plan",
        "chart_types": ["Scatter", "Line", "Bar", "Histogram"],
        "data_preview": "Data Preview",
        "statistical_summary": "Statistical Summary",
        "data_types": "Data Types",
        "missing_values": "Missing Values",
        "interactive_viz": "Interactive Visualizations",
        "chart_type": "Chart Type",
        "advanced_analysis": "Advanced Analysis",
        "analysis_type": "Analysis Type",
        "ml_insights": "Machine Learning Insights",
        "export_results": "Export Results",
        "download_csv": "Download CSV",
        "download_report": "Download Report",
        "save_database": "Save to Database",
        "dataset_name": "Dataset Name",
        "your_datasets": "Your Datasets",
        "created": "Created",
        "load": "Load",
        "delete": "Delete",
        "account_settings": "Account Settings",
        "preferences": "Preferences",
        "api_access": "API Access",
        "change_password": "Change Password",
        "current_password": "Current Password",
        "new_password": "New Password",
        "confirm_new_password": "Confirm New Password",
        "update_password": "Update Password",
        "theme": "Theme",
        "language": "Language",
        "auto_save": "Auto-save analyses",
        "save_preferences": "Save Preferences",
        "upgrade_plan": "Upgrade Your Plan",
        "current_plan": "Current Plan",
        "features": "Features",
        "upgrade": "Upgrade",
        "admin_panel": "Admin Panel",
        "user_management": "User Management",
        "system_analytics": "System Analytics",
        "total_users": "Total Users",
        "active_users": "Active Users",
        "pro_users": "Pro Users",
        "enterprise_users": "Enterprise Users",
        "total_datasets": "Total Datasets",
        "total_analyses": "Total Analyses",
        "system_health": "System Health",
        "clear_cache": "Clear Cache",
        "backup_db": "Backup Database",
        "health_check": "Health Check",
        "search_users": "Search users",
        "filter_type": "Filter by type",
        "filter_status": "Filter by status",
        "admin_notes": "Admin Notes",
        "reset_password": "Reset Password",
        "update": "Update",
        "bulk_operations": "Bulk Operations",
        "bulk_upgrade": "Bulk Upgrade",
        "apply_action": "Apply Action",
        # Payment System
        "payment_method": "Payment Method",
        "credit_card": "Credit Card",
        "paypal": "PayPal",
        "crypto": "Cryptocurrency",
        "bank_transfer": "Bank Transfer",
        "card_number": "Card Number",
        "expiry_date": "Expiry Date",
        "cvv": "CVV",
        "name_on_card": "Name on Card",
        "pay_now": "Pay Now",
        "payment_success": "Payment Successful!",
        "payment_failed": "Payment Failed",
        "processing_payment": "Processing your payment...",
        "select_duration": "Select Duration",
        "monthly": "Monthly",
        "yearly": "Yearly (Save 20%)",
        "lifetime": "Lifetime Access",
        "price": "Price",
        "currency": "USD",
        "total_amount": "Total Amount",
        "payment_details": "Payment Details",
        "billing_info": "Billing Information",
        "phone": "Phone Number",
        "address": "Address",
        "city": "City",
        "country": "Country",
        "zip_code": "ZIP Code"
    },
    "ar": {
        "title": "محلل البيانات المحترف",
        "login": "تسجيل الدخول",
        "signup": "إنشاء حساب",
        "username": "اسم المستخدم",
        "password": "كلمة المرور",
        "email": "البريد الإلكتروني",
        "confirm_password": "تأكيد كلمة المرور",
        "login_btn": "تسجيل الدخول",
        "sign_up_btn": "إنشاء حساب",
        "fill_fields": "يرجى ملء جميع الحقول",
        "account_exists": "الحساب موجود مسبقاً",
        "success_signup": "تم إنشاء الحساب بنجاح!",
        "error_login": "اسم المستخدم أو كلمة المرور غير صحيحة",
        "welcome": "مرحباً",
        "logout_btn": "تسجيل الخروج",
        "admin_dashboard": "لوحة تحكم المسؤول",
        "subscription_warning": "اشتراكك سينتهي خلال {days} يوم",
        "upload_file": "رفع مجموعة البيانات",
        "dashboard": "لوحة التحكم",
        "analytics": "التحليلات",
        "machine_learning": "التعلم الآلي",
        "data_management": "إدارة البيانات",
        "settings": "الإعدادات",
        "store": "ترقية الخطة",
        "chart_types": ["مبعثر", "خطي", "أعمدة", "هيستوجرام"],
        "data_preview": "معاينة البيانات",
        "statistical_summary": "ملخص إحصائي",
        "data_types": "أنواع البيانات",
        "missing_values": "القيم المفقودة",
        "interactive_viz": "تصورات تفاعلية",
        "chart_type": "نوع الرسم البياني",
        "advanced_analysis": "تحليل متقدم",
        "analysis_type": "نوع التحليل",
        "ml_insights": "رؤى التعلم الآلي",
        "export_results": "تصدير النتائج",
        "download_csv": "تحميل CSV",
        "download_report": "تحميل التقرير",
        "save_database": "حفظ في قاعدة البيانات",
        "dataset_name": "اسم مجموعة البيانات",
        "your_datasets": "مجموعات البيانات الخاصة بك",
        "created": "تم الإنشاء",
        "load": "تحميل",
        "delete": "حذف",
        "account_settings": "إعدادات الحساب",
        "preferences": "التفضيلات",
        "api_access": "الوصول إلى API",
        "change_password": "تغيير كلمة المرور",
        "current_password": "كلمة المرور الحالية",
        "new_password": "كلمة المرور الجديدة",
        "confirm_new_password": "تأكيد كلمة المرور الجديدة",
        "update_password": "تحديث كلمة المرور",
        "theme": "السمة",
        "language": "اللغة",
        "auto_save": "حفظ التحليلات تلقائياً",
        "save_preferences": "حفظ التفضيلات",
        "upgrade_plan": "ترقية خطتك",
        "current_plan": "الخطة الحالية",
        "features": "الميزات",
        "upgrade": "ترقية",
        "admin_panel": "لوحة المسؤول",
        "user_management": "إدارة المستخدمين",
        "system_analytics": "تحليلات النظام",
        "total_users": "إجمالي المستخدمين",
        "active_users": "المستخدمين النشطين",
        "pro_users": "مستخدمي Pro",
        "enterprise_users": "مستخدمي Enterprise",
        "total_datasets": "إجمالي مجموعات البيانات",
        "total_analyses": "إجمالي التحليلات",
        "system_health": "صحة النظام",
        "clear_cache": "مسح الذاكرة المؤقتة",
        "backup_db": "نسخ قاعدة البيانات احتياطياً",
        "health_check": "فحص الصحة",
        "search_users": "بحث في المستخدمين",
        "filter_type": "تصفية حسب النوع",
        "filter_status": "تصفية حسب الحالة",
        "admin_notes": "ملاحظات المسؤول",
        "reset_password": "إعادة تعيين كلمة المرور",
        "update": "تحديث",
        "bulk_operations": "العمليات المجمعة",
        "bulk_upgrade": "ترقية مجمعة",
        "apply_action": "تطبيق الإجراء",
        # Payment System
        "payment_method": "طريقة الدفع",
        "credit_card": "بطاقة ائتمان",
        "paypal": "باي بال",
        "crypto": "عملة مشفرة",
        "bank_transfer": "تحويل بنكي",
        "card_number": "رقم البطاقة",
        "expiry_date": "تاريخ الانتهاء",
        "cvv": "CVV",
        "name_on_card": "الاسم على البطاقة",
        "pay_now": "ادفع الآن",
        "payment_success": "تم الدفع بنجاح!",
        "payment_failed": "فشل في الدفع",
        "processing_payment": "جاري معالجة الدفع...",
        "select_duration": "اختر المدة",
        "monthly": "شهري",
        "yearly": "سنوي (وفر 20%)",
        "lifetime": "وصول مدى الحياة",
        "price": "السعر",
        "currency": "دولار",
        "total_amount": "المبلغ الإجمالي",
        "payment_details": "تفاصيل الدفع",
        "billing_info": "معلومات الفواتير",
        "phone": "رقم الهاتف",
        "address": "العنوان",
        "city": "المدينة",
        "country": "البلد",
        "zip_code": "الرمز البريدي"
    },
    "ckb": {
        "title": "پڕۆی شیکاری داتا",
        "login": "چوونەژوورەوە",
        "signup": "درووستکردنی هەژمار",
        "username": "ناوی بەکارهێنەر",
        "password": "وشەی نهێنی",
        "email": "ئیمەیڵ",
        "confirm_password": "پشتڕاستکردنی وشەی نهێنی",
        "login_btn": "چوونەژوورەوە",
        "sign_up_btn": "درووستکردنی هەژمار",
        "fill_fields": "تکایە هەموو خانەکان پڕبکەرەوە",
        "account_exists": "هەژمار پێشتر دروستکراوە",
        "success_signup": "هەژمار بە سەرکەوتوویی دروستکرا!",
        "error_login": "ناوی بەکارهێنەر یان وشەی نهێنی هەڵەیە",
        "welcome": "بەخێربێیت",
        "logout_btn": "چوونەدەرەوە",
        "admin_dashboard": "تەختی کارگێڕی",
        "subscription_warning": "بەشداریت لە {days} ڕۆژدا کۆتایی دێت",
        "upload_file": "بارکردنی داتا",
        "dashboard": "تەختە",
        "analytics": "شیکاری",
        "machine_learning": "فێربوونی ئامێر",
        "data_management": "بەڕێوەبردنی داتا",
        "settings": "ڕێکخستنەکان",
        "store": "پلەی بەرزکردن",
        "chart_types": ["پڕ", "هێڵ", "ستوون", "هیستۆگرام"],
        "data_preview": "پێشبینینی داتا",
        "statistical_summary": "کورتەی ئاماری",
        "data_types": "جۆرەکانی داتا",
        "missing_values": "نرخی ونبوو",
        "interactive_viz": "بینینە پێکەوەگرێدراوەکان",
        "chart_type": "جۆری هێڵکاری",
        "advanced_analysis": "شیکاری پێشکەوتوو",
        "analysis_type": "جۆری شیکاری",
        "ml_insights": "تێگەیشتنەکانی فێربوونی ئامێر",
        "export_results": "هەناردەی ئەنجامەکان",
        "download_csv": "داگرتنی CSV",
        "download_report": "داگرتنی ڕاپۆرت",
        "save_database": "پاشەکەوتکردن لە بنکەی داتا",
        "dataset_name": "ناوی کۆمەڵەی داتا",
        "your_datasets": "کۆمەڵە داتاکانی تۆ",
        "created": "درووستکرا",
        "load": "بارکردن",
        "delete": "سڕینەوە",
        "account_settings": "ڕێکخستنەکانی هەژمار",
        "preferences": "پەسەندکردنەکان",
        "api_access": "دەستگەیشتنی API",
        "change_password": "گۆڕینی وشەی نهێنی",
        "current_password": "وشەی نهێنی ئێستا",
        "new_password": "وشەی نهێنی نوێ",
        "confirm_new_password": "پشتڕاستکردنی وشەی نهێنی نوێ",
        "update_password": "نوێکردنەوەی وشەی نهێنی",
        "theme": "بابەت",
        "language": "زمان",
        "auto_save": "خۆکارانە پاشەکەوتکردنی شیکاریەکان",
        "save_preferences": "پاشەکەوتکردنی پەسەندکردنەکان",
        "upgrade_plan": "پلەی خۆت بەرزبکەرەوە",
        "current_plan": "پلەی ئێستا",
        "features": "تایبەتمەندییەکان",
        "upgrade": "بەرزکردنەوە",
        "admin_panel": "تەختی کارگێڕی",
        "user_management": "بەڕێوەبردنی بەکارهێنەران",
        "system_analytics": "شیکارییەکانی سیستەم",
        "total_users": "کۆی گشتی بەکارهێنەران",
        "active_users": "بەکارهێنەرانی چالاک",
        "pro_users": "بەکارهێنەرانی پرۆ",
        "enterprise_users": "بەکارهێنەرانی ئێنتەرپرایز",
        "total_datasets": "کۆی گشتی کۆمەڵە داتاکان",
        "total_analyses": "کۆی گشتی شیکارییەکان",
        "system_health": "تەندروستی سیستەم",
        "clear_cache": "پاککردنەوەی کەش",
        "backup_db": "پاشەکەوتی بنکەی داتا",
        "health_check": "پشکنینی تەندروستی",
        "search_users": "گەڕان لە بەکارهێنەران",
        "filter_type": "پاڵاوتن بەپێی جۆر",
        "filter_status": "پاڵاوتن بەپێی دۆخ",
        "admin_notes": "تێبینییەکانی کارگێڕ",
        "reset_password": "دووبارە ڕێکخستنی وشەی نهێنی",
        "update": "نوێکردنەوە",
        "bulk_operations": "کردارە کۆمەڵاییەکان",
        "bulk_upgrade": "بەرزکردنەوەی کۆمەڵایی",
        "apply_action": "جێبەجێکردنی کردار",
        # Payment System
        "payment_method": "ڕێگەی پارەدان",
        "credit_card": "کارتی بانکی",
        "paypal": "پەیپاڵ",
        "crypto": "دراوی کریپتۆ",
        "bank_transfer": "گوازینەوەی بانکی",
        "card_number": "ژمارەی کارت",
        "expiry_date": "بەرواری کۆتایی",
        "cvv": "CVV",
        "name_on_card": "ناو لەسەر کارت",
        "pay_now": "ئێستا بپەرێ",
        "payment_success": "پارەدان سەرکەوتووبوو!",
        "payment_failed": "پارەدان سەرکەوتوو نەبوو",
        "processing_payment": "پارەدانەکەت جێبەجێ دەکرێت...",
        "select_duration": "ماوە هەڵبژێرە",
        "monthly": "مانگانە",
        "yearly": "ساڵانە (20% هەڵوەرە)",
        "lifetime": "دەستگەیشتنی ژیانی",
        "price": "نرخ",
        "currency": "دۆلار",
        "total_amount": "کۆی گشتی",
        "payment_details": "وردەکارییەکانی پارەدان",
        "billing_info": "زانیاری پسوڵە",
        "phone": "ژمارەی تەلەفون",
        "address": "ناونیشان",
        "city": "شار",
        "country": "وڵات",
        "zip_code": "کۆدی پۆستی"
    }
}

def get_language(lang_code):
    """الحصول على قاموس اللغة المطلوبة"""
    return LANGUAGES.get(lang_code, LANGUAGES["en"])

def get_available_languages():
    """الحصول على اللغات المتاحة"""
    return {
        "en": "English 🇺🇸",
        "ar": "العربية 🇸🇦", 
        "ckb": "کوردیی سۆرانی 🇹🇯"
    }