# lang.py
languages = {
    "en": {
        "title": "📊 Web Data Analysis App",
        "login": "Login",
        "signup": "Sign Up",
        "username": "Username",
        "password": "Password",
        "sign_up_btn": "Sign Up",
        "login_btn": "Login",
        "welcome": "Welcome",
        "admin_dashboard": "Admin Dashboard",
        "user_dashboard": "User Dashboard",
        "upload_file": "Upload CSV or Excel file",
        "file_uploaded": "File uploaded successfully!",
        "select_x": "Select X column",
        "select_y": "Select Y column",
        "select_chart": "Select chart type",
        "chart_types": ["Scatter", "Line", "Bar", "Histogram"],
        "error_login": "Incorrect username or password!",
        "account_exists": "Username already exists!",
        "success_signup": "Account created successfully! Free account by default.",
        "subscription_warning": "Your subscription will expire in {days} days!"
    },
    "ar": {
        "title": "📊 تطبيق تحليل البيانات على الويب",
        "login": "تسجيل الدخول",
        "signup": "إنشاء حساب",
        "username": "اسم المستخدم",
        "password": "كلمة المرور",
        "sign_up_btn": "تسجيل",
        "login_btn": "دخول",
        "welcome": "مرحبًا",
        "admin_dashboard": "لوحة تحكم الأدمن",
        "user_dashboard": "لوحة المستخدم",
        "upload_file": "اختر ملف CSV أو Excel",
        "file_uploaded": "✅ تم رفع الملف بنجاح!",
        "select_x": "اختر العمود X",
        "select_y": "اختر العمود Y",
        "select_chart": "اختر نوع الرسم",
        "chart_types": ["نقطة", "خط", "أعمدة", "هيستوجرام"],
        "error_login": "اسم المستخدم أو كلمة المرور غير صحيحة!",
        "account_exists": "اسم المستخدم موجود بالفعل!",
        "success_signup": "تم إنشاء الحساب بنجاح! الحساب Free تلقائيًا.",
        "subscription_warning": "اشتراكك سينتهي بعد {days} أيام!"
    },
    "ku": {
        "title": "📊 Sepana Web Data Analysis",
        "login": "چوونەژوورەوە",
        "signup": "دروستکردنی هەژمار",
        "username": "ناوی بەکارهێنەر",
        "password": "تێپەڕەوشە",
        "sign_up_btn": "دروستکردن",
        "login_btn": "چوونەژوورەوە",
        "welcome": "به‌خێربێیت",
        "admin_dashboard": "پانێلی فەرمانی ئەدمین",
        "user_dashboard": "پانێلی بەکارهێنەر",
        "upload_file": "فایلی CSV یان Excel هەڵبژێرە",
        "file_uploaded": "✅ فایلی تەواوەتی هاتە بارکردن!",
        "select_x": "هەڵبژاردنی خانە X",
        "select_y": "هەڵبژاردنی خانە Y",
        "select_chart": "جۆری چارت هەڵبژێرە",
        "chart_types": ["Scatter", "Line", "Bar", "Histogram"],
        "error_login": "ناوی بەکارهێنەر یان تێپەڕەوشە هەڵەیە!",
        "account_exists": "ناوی بەکارهێنەر پێشتر هەیە!",
        "success_signup": "هەژمار دروستکرا! هەژمار Free بەشێوەی خۆکار.",
        "subscription_warning": "ماوەی بەدەست هاتنی ئەندامیت {days} ڕۆژە!"
    }
}
